// Allowlisted diagnostics only: never forward upstream message/details/stack/request payload.
const errorNames=new Set(['Error','TypeError','PostgrestError','StripeError','StripeInvalidRequestError','StripeAuthenticationError','StripePermissionError','StripeAPIError','StripeConnectionError','StripeRateLimitError','StripeCardError','BillingDiagnosticError']);
const stripeCodes=new Set(['resource_missing','api_key_expired','account_invalid','authentication_required','rate_limit','lock_timeout','idempotency_key_in_use','parameter_unknown','parameter_invalid_empty','parameter_invalid_integer','parameter_invalid_string_blank','card_declined','amount_too_small','amount_too_large']);
export type BillingDiagnostics={stage:string;errorName:string;safeMessage:string;supabaseCode:string|null;stripeCode:string|null;httpStatus:number|null};
const messages:Record<string,string>={PGRST202:'Required database function was not found in the API schema cache.',PGRST301:'Database credentials were rejected.',PGRST204:'Required database column was not found in the API schema cache.',PGRST205:'Required database table was not found in the API schema cache.','42P01':'Required database relation does not exist.','42883':'Required database function does not exist.','42501':'Database operation was denied by permissions.','23505':'Database uniqueness constraint rejected the operation.','23503':'Database foreign-key constraint rejected the operation.',resource_missing:'Required Stripe resource was not found.',api_key_expired:'Stripe credentials were rejected.'};
export class BillingDiagnosticError extends Error {readonly diagnostic:BillingDiagnostics;constructor(diagnostic:BillingDiagnostics){super(diagnostic.safeMessage);this.name='BillingDiagnosticError';this.diagnostic=diagnostic;}}
export function billingFailure(stage:string,error:unknown,source?:'supabase'|'stripe',status?:number){if(error instanceof BillingDiagnosticError)return new BillingDiagnosticError({...error.diagnostic,stage});const record=error&&typeof error==='object'?error as {name?:unknown;code?:unknown;type?:unknown}:{};const suppliedName=typeof record.name==='string'?record.name:typeof record.type==='string'?record.type:'Error';const errorName=errorNames.has(suppliedName)?suppliedName:'Error';const code=typeof record.code==='string'?record.code:'';const supabaseCode=source==='supabase'&&/^(?:[A-Z0-9]{5}|PGRST[0-9]{3})$/.test(code)?code:null;const stripeCode=source==='stripe'&&stripeCodes.has(code)?code:null;const safeMessage=messages[supabaseCode??stripeCode??'']??(source==='supabase'?'Billing database operation failed.':source==='stripe'?'Stripe billing operation failed.':'Billing operation failed.');return new BillingDiagnosticError({stage,errorName,safeMessage,supabaseCode,stripeCode,httpStatus:typeof status==='number'&&Number.isInteger(status)&&status>=100&&status<=599?status:null});}
export async function billingStep<T>(stage:string,operation:()=>Promise<T>,source?:'supabase'|'stripe'):Promise<T>{try{return await operation();}catch(error){throw billingFailure(stage,error,source);}}
export function logBillingFailure(error:unknown,fallbackStage:string){const diagnostic=error instanceof BillingDiagnosticError?error.diagnostic:billingFailure(fallbackStage,error).diagnostic;console.error('Toolgrain billing operation failed',diagnostic);}
