'use client';
import {trackToolgrainEvent} from '@/lib/analytics-events';
import {useAccount} from '@/components/auth/account-provider';
import {useEffect,useRef,useState} from 'react';
import {ShieldCheck} from 'lucide-react';
import {parseCsvFile,CsvError} from '@/lib/csv/parse-csv';
import type {ParsedCsv} from '@/lib/csv/types';
import {shopifyFields,shopifyFormatUrl} from '@/lib/shopify/fields';
import {suggestMappings} from '@/lib/shopify/mapping';
import {createSupplierSampleFile} from '@/lib/shopify/sample';
import {transformSupplier} from '@/lib/shopify/transform';
import {applyOutputEdit,createWorkingOutput,resetWorkingOutput,type WorkingOutput} from '@/lib/shopify/working';
import {canExport} from '@/lib/shopify/validate';
import {downloadShopifyCsv} from '@/lib/shopify/export';
import {defaultOptions,type Mapping,type TransformOptions,type ShopifyResult} from '@/lib/shopify/types';
import {ShopifyOutputPreview,type ShopifyRowFilter} from '../shopify-output-preview';
import {FileDropzone} from '../file-dropzone';
import {SelectedFiles} from '../selected-files';
import {WorkspaceShell} from '../workspace-shell';
import {plans} from '@/config/plans';
import {rowViolation,fileSizeViolation,fileSizeLimitMessage,type UsageViolation} from '@/lib/entitlements';
import {PlanIndicator,UpgradePrompt} from '../upgrade-prompt';
const acceptedTypes=['.csv'] as const;
const number=new Intl.NumberFormat('en');
export function SupplierCSVToShopify(){
 const plan=useAccount().plan;
 const [usage,setUsage]=useState<UsageViolation|null>(null);
 const [sampleLoaded,setSampleLoaded]=useState(false);
 const [reviewFilter,setReviewFilter]=useState<ShopifyRowFilter>('all');
 const [file,setFile]=useState<File|null>(null),[csv,setCsv]=useState<ParsedCsv|null>(null),[mapping,setMapping]=useState<Mapping>({}),[options,setOptions]=useState<TransformOptions>({...defaultOptions});
 const [working,setWorking]=useState<WorkingOutput|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[resetKey,setResetKey]=useState(0);
 const result:ShopifyResult|null=working?.result??null;
 const controller=useRef<AbortController|null>(null),resultRef=useRef<HTMLDivElement>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 const completedRun=useRef(false);
 const baseline=working?.baseline;
 useEffect(()=>{if(baseline)resultRef.current?.focus({preventScroll:true});},[baseline]);
 function invalidate(){setUsage(null);setWorking(null);setError('');}
 function remove(){controller.current?.abort();setSampleLoaded(false);setFile(null);setCsv(null);setMapping({});setOptions({...defaultOptions});setBusy(false);invalidate();setResetKey(value=>value+1);}
 async function select(selected:File,isSample=false){
  setSampleLoaded(isSample);setReviewFilter('all');
  controller.current?.abort();const abort=new AbortController();controller.current=abort;setFile(selected);setCsv(null);setMapping({});setOptions({...defaultOptions});invalidate();setBusy(true);
  try{const parsed=await parseCsvFile(selected,abort.signal);if(abort.signal.aborted)return;setCsv(parsed);const blocked=rowViolation(plan,'supplier-csv-to-shopify',parsed.rows.length,selected.name);setUsage(blocked);if(!blocked)setMapping(suggestMappings(parsed.columns));}
  catch(caught){if(!abort.signal.aborted)setError(caught instanceof CsvError?caught.message:'This CSV could not be read.');}
  finally{if(controller.current===abort)setBusy(false);}
 }
 function changeOptions(next:Partial<TransformOptions>){setOptions(current=>({...current,...next}));invalidate();}
 function renderMapping(field:typeof shopifyFields[number]){if(!csv)return null;return <label key={field} htmlFor={'shopify-'+field.replace(/\W/g,'-')}>{field} <span className="muted">{field==='Title'?'Required':'Optional'}</span><select id={'shopify-'+field.replace(/\W/g,'-')} aria-label={'Map '+field} value={mapping[field]??''} onChange={event=>{setMapping(current=>({...current,[field]:event.target.value||undefined}));invalidate();}}><option value="">{field==='URL handle'?'Generate from Title':field==='Status'||field==='Published on online store'?'Use default':'No mapping — omit field'}</option>{csv.columns.map((column,index)=><option value={column.key} key={column.key}>{column.name}{csv.columns.filter(c=>c.name===column.name).length>1?' (column '+(index+1)+')':''}</option>)}</select></label>;}
 const stage=!csv||usage?'Upload':!result?'Map':canExport(result)?'Export':'Review';
 return <div className="shopify-workspace"><ol className="shopify-progress" aria-label="Conversion progress">{['Upload','Map','Review','Export'].map((step,index)=>{const completed=index<['Upload','Map','Review','Export'].indexOf(stage);return <li key={step} className={completed?'is-complete':undefined} aria-current={step===stage?'step':undefined}><span className="shopify-step-number" aria-hidden="true">{completed?'✓':index+1}</span><span>{step}<span className="sr-only">{completed?': completed':step===stage?': current step':': upcoming'}</span></span></li>;})}</ol><WorkspaceShell state={busy?'processing':result?'result':error&&!csv?'error':csv?'file-selected':'idle'}
 upload={<><PlanIndicator tool="supplier-csv-to-shopify"/><FileDropzone compactContent={file&&<SelectedFiles files={[file]} onRemove={remove} showRemove={false} metadata={<><span role="status">{busy?'Reading CSV…':csv?number.format(csv.rows.length)+' products · Ready to map':'File selected'}</span>{sampleLoaded&&<span className="shopify-demo-badge">Fictional sample data</span>}</>}/>} compactActions={<button type="button" className="button ghost" onClick={remove}>Remove</button>} key={resetKey} acceptedTypes={acceptedTypes} multiple={false} maxFileSize={plans[plan].fileSizeBytes} fileSizeError={file=>fileSizeLimitMessage(plan,file.size)} onFileSizeRejected={file=>setUsage(fileSizeViolation(plan,'supplier-csv-to-shopify',file.size,file.name))} title="Drop your supplier CSV here" fileTypeLabel="CSV" fileTypeError="This tool supports CSV files only." onFilesSelected={files=>{void select(files[0]);}} onValidationChange={message=>{if(message){controller.current?.abort();setCsv(null);setBusy(false);invalidate();setError(message);}}}/><div className="supplier-sample">{!sampleLoaded&&<><button type="button" className="button secondary" disabled={busy} onClick={()=>{void select(createSupplierSampleFile(),true);}}>Try with sample CSV</button><p className="muted">Explore 14 fictional products with intentional errors to practise corrections.</p></>}</div>{csv&&<>{csv.warnings.map(warning=><p className="compare-warning" key={warning}>{warning}</p>)}</>}{usage&&<UpgradePrompt usage={usage}/>}<p className="muted shopify-limitations">For new simple products only. No variants, multiple images or existing-product synchronization.</p></>}
 settings={csv&&!usage&&<><div className="shopify-mapping-header"><h2>Map product columns</h2><span className="shopify-mapping-count" role="status">{shopifyFields.filter(field=>!!mapping[field]).length} mapped</span></div><p className="muted">Review the suggested columns. Title is required; all other mappings are optional. Unmapped handles are generated from Title.</p><div className="shopify-mapping-grid">{shopifyFields.filter(field=>['Title','SKU','Description','Price','Inventory quantity','Type'].includes(field)).map(field=>renderMapping(field))}</div><details className="shopify-optional-mappings"><summary>More optional mappings</summary><p className="muted">Product category requires Shopify taxonomy values. Type is a free-form supplier category; this tool does not reconcile categories.</p><div className="shopify-mapping-grid">{shopifyFields.filter(field=>!['Title','SKU','Description','Price','Inventory quantity','Type'].includes(field)).map(field=>renderMapping(field))}</div></details>
 <h3>Import defaults</h3><p className="muted">Defaults apply only when the corresponding field is unmapped.</p><div className="compare-key-grid"><label>Status default<select aria-label="Status default" value={options.status} onChange={e=>changeOptions({status:e.target.value as TransformOptions['status']})}><option value="draft">draft</option><option value="active">active</option><option value="archived">archived</option></select></label><label>Published on online store default<select aria-label="Published on online store default" value={String(options.published)} onChange={e=>changeOptions({published:e.target.value==='true'})}><option value="false">false</option><option value="true">true</option></select></label><label>Price format<select aria-label="Price format" value={options.priceFormat} onChange={e=>changeOptions({priceFormat:e.target.value as TransformOptions['priceFormat']})}><option value="auto">Auto</option><option value="comma">Decimal comma</option><option value="point">Decimal point</option></select></label></div>
 {mapping['URL handle']&&<label className="shopify-handle-option"><input type="checkbox" checked={options.uniqueMappedHandles} onChange={e=>changeOptions({uniqueMappedHandles:e.target.checked})}/>Make duplicate handles unique</label>}
 <p className="muted">Shopify&apos;s product CSV inventory quantity is intended for single-location stores. Multi-location inventory uses a separate inventory workflow.</p><p className="muted">Shopify needs publicly accessible image URLs to import product images. Toolgrain does not fetch images or check availability.</p></>}
 action={<button className="button" type="button" disabled={!csv||busy||!!usage} onClick={()=>{if(csv&&!usage){completedRun.current=false;trackToolgrainEvent('tool_started',{tool:'supplier-shopify',plan});setReviewFilter('all');const next=createWorkingOutput(transformSupplier(csv,mapping,options));setWorking(next);setError('');if(canExport(next.result)){completedRun.current=true;trackToolgrainEvent('tool_completed',{tool:'supplier-shopify',plan});}}}}>Validate and preview</button>}
 error={error&&<p role="alert" className="file-error">{error}</p>}
 result={result&&<div ref={resultRef} tabIndex={-1} className="analysis-focus" aria-label="Shopify validation result"><h2>Shopify output preview</h2><dl className="shopify-summary">{Object.entries({Products:result.summary.products,'Mapped fields':result.summary.mappedFields,'Generated handles':result.summary.generatedHandles,Errors:result.summary.errors,Warnings:result.summary.warnings}).map(([label,count])=><div key={label}><dt>{label}</dt><dd>{number.format(count)}</dd></div>)}</dl>
 <button type="button" className="button ghost" disabled={!working?.edits} onClick={()=>setWorking(current=>current?resetWorkingOutput(current):null)}>Reset changes</button><p role="status" className="muted">{working?.edits??0} committed corrections · {result.summary.errors} errors · {result.summary.warnings} warnings</p><ShopifyOutputPreview filter={reviewFilter} onFilterChange={setReviewFilter} key={working?.resetEpoch} result={result} onEdit={(row,field,value)=>{if(!working)return [];const next=applyOutputEdit(working,row,field,value,options);setWorking(next);if(!completedRun.current&&canExport(next.result)){completedRun.current=true;trackToolgrainEvent('tool_completed',{tool:'supplier-shopify',plan});}return next.result.issues.filter(issue=>issue.severity==='error'&&issue.field===field&&issue.rows.includes(row)).map(issue=>issue.message);}}/>
 <p>Toolgrain prepares the file for Shopify&apos;s product CSV format. Always review Shopify&apos;s import preview before completing an import.</p><p className="muted">This file is for new simple products. Do not use it to overwrite existing products with variants. <a className="text-link" href={shopifyFormatUrl} target="_blank" rel="noreferrer">Shopify product CSV documentation</a></p>
 <button className="button" type="button" disabled={!canExport(result)} onClick={()=>{try{if(!canExport(result))return;downloadShopifyCsv(result,file?.name??'supplier-products.csv');trackToolgrainEvent('export_clicked',{tool:'supplier-shopify',plan});setError('');}catch{setError('This Shopify CSV could not be prepared. Review errors and try again.');}}}>Download Shopify CSV</button>{error&&<p role="alert" className="file-error">{error}</p>}{!canExport(result)&&<div className="shopify-export-blocked"><p role="status">{result.summary.errors} blocking errors remain. Correct them before downloading.</p><button type="button" className="button secondary" onClick={()=>{setReviewFilter('error');requestAnimationFrame(()=>resultRef.current?.querySelector<HTMLElement>('.shopify-filter-bar button[aria-pressed=true]')?.focus());}}>Review blocking issues</button></div>}</div>}
 note={<p><ShieldCheck size={15} aria-hidden="true"/>Your file stays on your device. Parsing, mapping, validation and export run locally in your browser. No CSV contents are uploaded.</p>}/></div>
}
