import {describe,it,expect,vi,beforeEach} from 'vitest';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import type {SupabaseClient} from '@supabase/supabase-js';
import {safeReturnPath} from '../src/lib/auth/return-path';
import {resolveProfilePlan,anonymousAccount} from '../src/lib/auth/account-data';
import {performAuth,performSignOut} from '../src/lib/auth/auth-service';
import {authErrorMessage} from '../src/lib/auth/errors';
import {confirmAuth} from '../src/lib/auth/callback';
import {AccountContent} from '../src/components/auth/account-content';
import {AccountProvider} from '../src/components/auth/account-provider';
import {PlanIndicator} from '../src/components/tools/upgrade-prompt';
import {canProcessRows,getToolLimit} from '../src/lib/entitlements';
import {plans} from '../src/config/plans';
import {supabaseConfig} from '../src/lib/supabase/config';
vi.mock('server-only',()=>({}));
vi.mock('../src/lib/supabase/server',()=>({createSupabaseServerClient:vi.fn()}));
vi.mock('next/navigation',()=>({redirect:vi.fn((path:string)=>{throw new Error('REDIRECT:'+path);})}));
import {createSupabaseServerClient} from '../src/lib/supabase/server';
import {getAccount} from '../src/lib/auth/account';
import AccountPage from '../src/app/account/page';
const input={email:'person@example.com',password:'Password123!',next:'/pricing'};
function fake(){const auth={signInWithPassword:vi.fn().mockResolvedValue({error:null}),signUp:vi.fn().mockResolvedValue({data:{session:null},error:null}),signInWithOtp:vi.fn().mockResolvedValue({error:null}),signOut:vi.fn().mockResolvedValue({error:null}),verifyOtp:vi.fn().mockResolvedValue({error:null}),exchangeCodeForSession:vi.fn().mockResolvedValue({error:null}),getUser:vi.fn().mockResolvedValue({data:{user:{id:'own',email:input.email}},error:null})};const single=vi.fn().mockResolvedValue({data:{id:'own',email:input.email,plan:'free',created_at:'2026-10-06',updated_at:'2026-10-06'},error:null}),eq=vi.fn().mockReturnValue({maybeSingle:single}),select=vi.fn().mockReturnValue({eq}),from=vi.fn().mockReturnValue({select});return {auth,single,eq,select,from,client:{auth,from} as unknown as SupabaseClient};}
beforeEach(()=>{vi.clearAllMocks();vi.unstubAllEnvs();vi.mocked(createSupabaseServerClient).mockResolvedValue(null);});
describe('account auth and trusted plans',()=>{
 it('anonymous user resolves to Free and keeps tool access',async()=>{expect(await getAccount()).toEqual(anonymousAccount);expect(canProcessRows('free','crm-csv-cleaner',500)).toBe(true);expect(canProcessRows('free','supplier-csv-to-shopify',100)).toBe(true);});
 it.each(['free','pro'] as const)('trusted %s profile determines central limits',async plan=>{const f=fake();f.single.mockResolvedValue({data:{id:'own',plan},error:null});vi.mocked(createSupabaseServerClient).mockResolvedValue(f.client);const account=await getAccount();expect(account.plan).toBe(plan);expect(getToolLimit(account.plan,'crm-csv-cleaner')).toBe(plans[plan].limits['crm-csv-cleaner']);expect(f.eq).toHaveBeenCalledWith('id','own');});
 it('ignores profile plan for another user',()=>expect(resolveProfilePlan('own',{id:'other',plan:'pro'})).toBe('free'));
 it('unverified identities and unknown plans fail closed',()=>{expect(resolveProfilePlan(null,{id:'own',plan:'pro'})).toBe('free');expect(resolveProfilePlan('own',{id:'own',plan:'enterprise'})).toBe('free');});
 it('ignores forged user metadata and auth errors',async()=>{const f=fake();f.auth.getUser.mockResolvedValue({data:{user:{id:'own',email:input.email,user_metadata:{plan:'pro'}}},error:{message:'forged'}});vi.mocked(createSupabaseServerClient).mockResolvedValue(f.client);expect((await getAccount()).plan).toBe('free');});
 it('missing profile and provider outage remain Free',async()=>{const f=fake();f.single.mockResolvedValue({data:null,error:{message:'outage'}});vi.mocked(createSupabaseServerClient).mockResolvedValue(f.client);expect((await getAccount()).plan).toBe('free');});
 it('account route rejects anonymous access with safe return',async()=>await expect(AccountPage()).rejects.toThrow('REDIRECT:/login?next=%2Faccount'));
 it.each(['/pricing','/tools/csv-compare','/account','/about','/'])('accepts internal return %s',path=>expect(safeReturnPath(path)).toBe(path));
 it.each(['https://evil.example','//evil.example','/\\evil.example','/%2f%2fevil.example','/%5cevil.example','/%252fevil.example','/login','/auth/callback','javascript:alert(1)','/pricing\n'])('rejects unsafe return %s',path=>expect(safeReturnPath(path)).toBe('/account'));
 it('strips query/hash from allowed paths',()=>expect(safeReturnPath('/pricing?plan=pro#x')).toBe('/pricing'));
 it('successful password login redirects internally',async()=>{const f=fake();expect(await performAuth(f.client,'login',input,'https://toolgrain.com')).toEqual({redirect:'/pricing'});expect(f.auth.signInWithPassword).toHaveBeenCalledWith({email:input.email,password:input.password});});
 it('unconfigured login provides honest fallback',async()=>expect((await performAuth(null,'login',input,'https://toolgrain.com')).error).toContain('not available yet'));
 it('signup sends auth fields only and handles confirmation',async()=>{const f=fake();const result=await performAuth(f.client,'signup',{...input,...{plan:'pro',csvContents:'private'}} as typeof input,'https://toolgrain.com');expect(result.message).toContain('Check your email');expect(f.auth.signUp).toHaveBeenCalledWith({email:input.email,password:input.password,options:{emailRedirectTo:'https://toolgrain.com/auth/callback?next=%2Fpricing'}});expect(JSON.stringify(f.auth.signUp.mock.calls)).not.toContain('csvContents');expect(JSON.stringify(f.auth.signUp.mock.calls)).not.toContain('"plan"');});
 it('signup handles configured confirmation-off session',async()=>{const f=fake();f.auth.signUp.mockResolvedValue({data:{session:{}},error:null});expect((await performAuth(f.client,'signup',input,'https://toolgrain.com')).redirect).toBe('/pricing');});
 it.each(['login','signup'] as const)('%s never exposes raw provider messages',async operation=>{const f=fake();f.auth.signInWithPassword.mockResolvedValue({error:{message:'SECRETSTACK',code:'invalid_credentials'}});f.auth.signUp.mockResolvedValue({data:{session:null},error:{message:'SECRETSTACK',code:'user_already_exists'}});const result=await performAuth(f.client,operation,input,'https://toolgrain.com');expect(result.error).toBeTruthy();expect(JSON.stringify(result)).not.toContain('SECRETSTACK');});
 it('network failures render a fixed message',async()=>{const f=fake();f.auth.signInWithPassword.mockRejectedValue(Error('private network details'));expect((await performAuth(f.client,'login',input,'https://toolgrain.com')).error).toBe('Unable to connect to the sign-in service. Please try again.');});
 it('magic links use existing accounts and safe callbacks',async()=>{const f=fake();await performAuth(f.client,'magic',{...input,next:'https://evil.example'},'https://toolgrain.com');expect(f.auth.signInWithOtp).toHaveBeenCalledWith({email:input.email,options:{emailRedirectTo:'https://toolgrain.com/auth/callback?next=%2Faccount',shouldCreateUser:false}});});
 it('signout invokes provider and handles safe failure',async()=>{const f=fake();expect(await performSignOut(f.client)).toEqual({});expect(f.auth.signOut).toHaveBeenCalledOnce();f.auth.signOut.mockResolvedValue({error:{message:'SECRET',code:'unknown'}});expect((await performSignOut(f.client)).error).toBe('Sign out failed. Please try again.');});
 it('callback verifies allowed OTP and prevents open redirects',async()=>{const f=fake();expect(await confirmAuth(f.client,new URLSearchParams({token_hash:'test',type:'email',next:'//evil.example'}))).toBe('/account');expect(f.auth.verifyOtp).toHaveBeenCalledWith({token_hash:'test',type:'email'});});
 it('expired OTP and disallowed type return fixed link error',async()=>{const f=fake();f.auth.verifyOtp.mockResolvedValue({error:{message:'SECRET'}});expect(await confirmAuth(f.client,new URLSearchParams({token_hash:'test',type:'email'}))).toBe('/login?error=link');expect(await confirmAuth(f.client,new URLSearchParams({token_hash:'test',type:'recovery'}))).toBe('/login?error=link');});
 it('PKCE callback supports safe internal returns',async()=>{const f=fake();expect(await confirmAuth(f.client,new URLSearchParams({code:'test',next:'/pricing'}))).toBe('/pricing');expect(f.auth.exchangeCodeForSession).toHaveBeenCalledWith('test');});
 it('account displays escaped user email and central plan',()=>{const html=renderToStaticMarkup(createElement(AccountContent,{account:{user:{id:'own',email:'<script>@example.com'},profile:null,plan:'free',profileAvailable:false}}));expect(html).toContain('&lt;script&gt;@example.com');expect(html).toContain('Free plan');expect(html).toContain('Pro subscriptions are coming soon');});
 it('read-only provider drives the tool indicator with trusted Pro',()=>{const html=renderToStaticMarkup(createElement(AccountProvider,{plan:'pro',signedIn:true},createElement(PlanIndicator,{tool:'supplier-csv-to-shopify'})));expect(html).toContain('10,000');expect(html).toContain('Pro');});
 it('requires public publishable keys and rejects secret keys',()=>{vi.stubEnv('NEXT_PUBLIC_SUPABASE_URL','https://project.supabase.co');vi.stubEnv('NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY','sb_secret_private');expect(supabaseConfig()).toBe(null);vi.stubEnv('NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY','sb_publishable_example');expect(supabaseConfig()).toMatchObject({url:'https://project.supabase.co'});});
 it('maps expired-link message without leaking details',()=>expect(authErrorMessage('otp_expired','magic')).toContain('expired'));
});
