import {describe,it,expect,vi,beforeEach} from 'vitest';
import type Stripe from 'stripe';
import {readFileSync} from 'node:fs';
import {subscriptionPlan,subscriptionSnapshot,selectSubscription,parseBillingCycle} from '../src/lib/stripe/entitlement';
import {startCheckout,startPortal,processBillingEvent} from '../src/lib/stripe/service';
import type {BillingRepository} from '../src/lib/stripe/repository';
import {canProcessRows} from '../src/lib/entitlements';
vi.mock('server-only',()=>({}));
const prices={monthly:'price_month',annual:'price_year'},user={id:'user-one',email:'account@example.invalid'};
function sub(status='active',price='price_month',created=1){return {id:'sub_one',customer:'cus_one',created,status,cancel_at_period_end:false,items:{data:[{quantity:1,price:{id:price},current_period_end:1800000000}]}} as unknown as Stripe.Subscription;}
function fake(){const subscriptions:Stripe.Subscription[]=[];const list=vi.fn(()=>({[Symbol.asyncIterator]:async function*(){for(const s of subscriptions)yield s;}}));const stripe={customers:{create:vi.fn(async()=>({id:'cus_one'}))},prices:{retrieve:vi.fn(async(id:string)=>({active:true,currency:'eur',unit_amount:id===prices.monthly?890:6900,recurring:{interval:id===prices.monthly?'month':'year',interval_count:1}}))},subscriptions:{list,retrieve:vi.fn(async(id:string)=>subscriptions.find(s=>s.id===id))},checkout:{sessions:{list:vi.fn(async()=>({data:[]})),expire:vi.fn(),create:vi.fn(async()=>({url:'https://checkout.stripe.com/test'}))}},billingPortal:{sessions:{create:vi.fn(async()=>({url:'https://billing.stripe.com/test'}))}}};const repo={profile:vi.fn(async()=>({id:user.id,plan:'free',stripe_customer_id:'cus_one'})),lock:vi.fn(async()=> 'lease'),release:vi.fn(),link:vi.fn(),write:vi.fn(),userForCustomer:vi.fn(async()=>user.id)};return {stripe:stripe as unknown as Stripe,repo:repo as unknown as BillingRepository,mocks:stripe,r:repo,subscriptions};}
beforeEach(()=>vi.clearAllMocks());
describe('billing entitlement',()=>{
 it.each(['active','trialing','past_due'])('%s keeps Pro for approved price',status=>expect(subscriptionPlan(status,prices.monthly,Object.values(prices))).toBe('pro'));
 it.each(['canceled','unpaid','incomplete_expired','incomplete','paused','unknown'])('%s downgrades to Free',status=>expect(subscriptionPlan(status,prices.monthly,Object.values(prices))).toBe('free'));
 it('unknown active prices never grant Pro',()=>expect(subscriptionPlan('active','price_other',Object.values(prices))).toBe('free'));
 it('scheduled cancellation retains Pro until actual status changes',()=>{const s=sub();s.cancel_at_period_end=true;expect(subscriptionSnapshot(s,Object.values(prices)).plan).toBe('pro');});
 it('stores item period end correctly',()=>expect(subscriptionSnapshot(sub(),Object.values(prices)).subscription_current_period_end).toBe(new Date(1800000000*1000).toISOString()));
 it('extra items and quantities fail closed',()=>{const s=sub();s.items.data.push(s.items.data[0]);expect(subscriptionSnapshot(s,Object.values(prices)).plan).toBe('free');});
 it('a later canceled old subscription does not revoke another entitled one',()=>expect(selectSubscription([sub('canceled',prices.monthly,8),sub('active',prices.annual,2)],Object.values(prices))?.status).toBe('active'));
 it('Free remains usable after downgrade',()=>expect(canProcessRows(subscriptionPlan('unpaid',prices.monthly,Object.values(prices)),'crm-csv-cleaner',500)).toBe(true));
 it.each(['price_arbitrary','https://evil','',null])('rejects browser cycle %s',cycle=>expect(parseBillingCycle(cycle)).toBeNull());
});
describe('secure checkout and portal',()=>{
 it('anonymous checkout redirects before any Stripe calls',async()=>{const f=fake();expect(await startCheckout(f.stripe,f.repo,null,'monthly',prices)).toEqual({url:'/login?next=%2Fpricing'});expect(f.r.lock).not.toHaveBeenCalled();expect(f.mocks.customers.create).not.toHaveBeenCalled();});
 it.each(['monthly','annual'] as const)('maps %s to server price and subscription mode',async cycle=>{const f=fake();await startCheckout(f.stripe,f.repo,user,cycle,prices);expect(f.mocks.checkout.sessions.create).toHaveBeenCalledWith(expect.objectContaining({mode:'subscription',customer:'cus_one',line_items:[{price:prices[cycle],quantity:1}]}),expect.anything());expect(f.r.write).not.toHaveBeenCalled();});
 it('rejects arbitrary price input without customer access',async()=>{const f=fake();expect((await startCheckout(f.stripe,f.repo,user,'price_evil',prices)).error).toBeTruthy();expect(f.r.lock).not.toHaveBeenCalled();});
 it('reuses existing customer',async()=>{const f=fake();await startCheckout(f.stripe,f.repo,user,'monthly',prices);expect(f.mocks.customers.create).not.toHaveBeenCalled();});
 it('creates and links missing customer with idempotency',async()=>{const f=fake();f.r.profile.mockResolvedValue({id:user.id,plan:'free',stripe_customer_id:null} as never);await startCheckout(f.stripe,f.repo,user,'monthly',prices);expect(f.mocks.customers.create).toHaveBeenCalledWith({email:user.email,metadata:{supabase_user_id:user.id}},{idempotencyKey:'toolgrain-customer-'+user.id});expect(f.r.link).toHaveBeenCalledWith(user.id,'lease','cus_one');});
 it('Pro cannot open another subscription',async()=>{const f=fake();f.r.profile.mockResolvedValue({id:user.id,plan:'pro',stripe_customer_id:'cus_one'});expect((await startCheckout(f.stripe,f.repo,user,'monthly',prices)).url).toBe('/account');expect(f.mocks.checkout.sessions.create).not.toHaveBeenCalled();});
 it('unconfirmed active subscription blocks duplicate checkout',async()=>{const f=fake();f.subscriptions.push(sub());expect((await startCheckout(f.stripe,f.repo,user,'annual',prices)).url).toBe('/account?billing=pending');expect(f.mocks.checkout.sessions.create).not.toHaveBeenCalled();});
 it('reuses open checkout session',async()=>{const f=fake();f.mocks.checkout.sessions.list.mockResolvedValue({data:[{id:'cs_one',mode:'subscription',status:'open',metadata:{billing_cycle:'monthly'},url:'https://checkout.stripe.com/existing'}]} as never);expect((await startCheckout(f.stripe,f.repo,user,'monthly',prices)).url).toContain('existing');expect(f.mocks.checkout.sessions.create).not.toHaveBeenCalled();});
 it('incorrect currency/amount is rejected before checkout',async()=>{const f=fake();f.mocks.prices.retrieve.mockResolvedValue({active:true,currency:'usd',unit_amount:890,recurring:{interval:'month',interval_count:1}});await expect(startCheckout(f.stripe,f.repo,user,'monthly',prices)).rejects.toThrow();expect(f.mocks.checkout.sessions.create).not.toHaveBeenCalled();expect(f.r.release).toHaveBeenCalled();});
 it('portal needs authentication',async()=>{const f=fake();expect((await startPortal(f.stripe,f.repo,null)).url).toContain('/login');expect(f.mocks.billingPortal.sessions.create).not.toHaveBeenCalled();});
 it('portal uses own customer only',async()=>{const f=fake();await startPortal(f.stripe,f.repo,user);expect(f.mocks.billingPortal.sessions.create).toHaveBeenCalledWith({customer:'cus_one',return_url:'https://toolgrain.com/account'});});
 it('billing payloads contain only billing/account identifiers',async()=>{const f=fake();await startCheckout(f.stripe,f.repo,{...user,filename:'secret.csv',rows:['secret']} as typeof user,'annual',prices);const payload=JSON.stringify(f.mocks.checkout.sessions.create.mock.calls);expect(payload).not.toContain('secret.csv');expect(payload).not.toContain('rows');expect(payload).not.toContain(user.email);expect(f.r.write).not.toHaveBeenCalled();});
});
describe('authoritative webhook synchronization',()=>{
 function event(type='customer.subscription.updated'){return {type,data:{object:{customer:'cus_one',status:'canceled'}}} as unknown as Stripe.Event;}
 it('retrieves fresh subscription rather than stale payload',async()=>{const f=fake();f.subscriptions.push(sub());await processBillingEvent(f.stripe,f.repo,event(),prices);expect(f.mocks.subscriptions.retrieve).toHaveBeenCalledWith('sub_one');expect(f.r.write).toHaveBeenCalledWith(user.id,'lease','cus_one',expect.objectContaining({plan:'pro',stripe_subscription_status:'active'}));});
 it('retries produce identical snapshots',async()=>{const f=fake();f.subscriptions.push(sub());await processBillingEvent(f.stripe,f.repo,event(),prices);await processBillingEvent(f.stripe,f.repo,event(),prices);expect(f.r.write.mock.calls[0]).toEqual(f.r.write.mock.calls[1]);});
 it('deletion with current canceled state downgrades',async()=>{const f=fake();f.subscriptions.push(sub('canceled'));await processBillingEvent(f.stripe,f.repo,event('customer.subscription.deleted'),prices);expect(f.r.write).toHaveBeenCalledWith(user.id,'lease','cus_one',expect.objectContaining({plan:'free'}));});
 it('unlinked customer is retriable and not email matched',async()=>{const f=fake();f.r.userForCustomer.mockResolvedValue(undefined as never);await expect(processBillingEvent(f.stripe,f.repo,event(),prices)).rejects.toThrow('Unlinked');expect(f.r.write).not.toHaveBeenCalled();});
 it('failure releases lock and does not acknowledge success',async()=>{const f=fake();f.r.write.mockRejectedValue(new Error('db'));await expect(processBillingEvent(f.stripe,f.repo,event(),prices)).rejects.toThrow();expect(f.r.release).toHaveBeenCalled();});
 it('unrelated events are ignored',async()=>{const f=fake();await processBillingEvent(f.stripe,f.repo,event('customer.created'),prices);expect(f.r.lock).not.toHaveBeenCalled();});
 it('RLS grants no browser billing writes or RPC execution',()=>{const sql=readFileSync('supabase/migrations/202610070001_billing.sql','utf8');expect(sql).toContain('from public,anon,authenticated');expect(sql).toContain('to service_role');expect(sql).not.toMatch(/grant\s+(?:update|insert|delete).*authenticated/i);expect(sql).toContain('expires_at>now() for update');});
 it('success view never writes entitlement',()=>{const source=readFileSync('src/components/auth/billing-status.tsx','utf8');expect(source).toContain('router.refresh()');expect(source).not.toContain('localStorage');expect(source).not.toContain('.update(');expect(source).not.toContain('Payment received');});
});
