import {describe,it,expect,vi,afterEach} from 'vitest';
import {readFileSync} from 'node:fs';
import {billingFailure,billingStep,logBillingFailure} from '../src/lib/stripe/diagnostics';
import {startCheckout} from '../src/lib/stripe/service';
import type Stripe from 'stripe';
import type {BillingRepository} from '../src/lib/stripe/repository';
vi.mock('server-only',()=>({}));
afterEach(()=>vi.restoreAllMocks());
describe('safe checkout diagnostics',()=>{
 it('reports missing RPC stage and PostgREST code without upstream text',()=>{const error=billingFailure('checkout.lock.acquire',{code:'PGRST202',message:'secret cookie customer@example.com',details:'CSV row',hint:'private'},'supabase');const log=vi.spyOn(console,'error').mockImplementation(()=>{});logBillingFailure(error,'checkout.start');expect(log).toHaveBeenCalledWith('Toolgrain billing operation failed',{stage:'checkout.lock.acquire',errorName:'Error',safeMessage:'Required database function was not found in the API schema cache.',supabaseCode:'PGRST202',stripeCode:null});expect(JSON.stringify(log.mock.calls)).not.toContain('secret');expect(JSON.stringify(log.mock.calls)).not.toContain('CSV');expect(JSON.stringify(error)).not.toContain('cookie');});
 it.each(['42P01','42501','23505','23503'])('retains database code %s',code=>expect(billingFailure('checkout.profile.read',{name:'PostgrestError',code,message:'private'},'supabase').diagnostic.supabaseCode).toBe(code));
 it('records safe Stripe error name and code',()=>{const d=billingFailure('checkout.price.retrieve',{name:'StripeInvalidRequestError',code:'resource_missing',message:'price private secret'},'stripe').diagnostic;expect(d.stripeCode).toBe('resource_missing');expect(d.errorName).toBe('StripeInvalidRequestError');expect(d.safeMessage).not.toContain('private');});
 it('does not log arbitrary names/codes/messages/stacks',()=>{const log=vi.spyOn(console,'error').mockImplementation(()=>{});logBillingFailure({name:'sk_live_secret',code:'sk_live_secret',message:'email@example.com',stack:'cookie secret'},'checkout.start');expect(JSON.stringify(log.mock.calls)).not.toContain('sk_live');expect(JSON.stringify(log.mock.calls)).not.toContain('@');expect(JSON.stringify(log.mock.calls)).not.toContain('cookie');});
 it('keeps Supabase code while setting the checkout operation stage',async()=>{const inner=billingFailure('billing.lock.acquire',{code:'PGRST202'},'supabase');await expect(billingStep('checkout.lock.acquire',async()=>{throw inner;},'supabase')).rejects.toMatchObject({diagnostic:{stage:'checkout.lock.acquire',supabaseCode:'PGRST202'}});});
 it('missing acquire RPC fails before profile and every Stripe call',async()=>{const stripe={customers:{create:vi.fn()},subscriptions:{list:vi.fn()},checkout:{sessions:{create:vi.fn()}}};const repo={lock:vi.fn(async()=>{throw billingFailure('billing.lock.acquire',{code:'PGRST202',message:'raw private'},'supabase');}),profile:vi.fn(),release:vi.fn()};await expect(startCheckout(stripe as unknown as Stripe,repo as unknown as BillingRepository,{id:'own',email:'test@example.invalid'},'monthly',{monthly:'price_month',annual:'price_year'})).rejects.toMatchObject({diagnostic:{stage:'checkout.lock.acquire',supabaseCode:'PGRST202'}});expect(repo.profile).not.toHaveBeenCalled();expect(stripe.customers.create).not.toHaveBeenCalled();expect(stripe.subscriptions.list).not.toHaveBeenCalled();});
 it('repair SQL is safe to rerun on existing billing columns',()=>{const sql=readFileSync('supabase/migrations/202610070001_billing.sql','utf8');expect(sql).not.toMatch(/\bdo \$(?!\$)|end;\$(?!\$);/);expect(sql.match(/\$\$/g)).toHaveLength(12);expect(sql.match(/add column if not exists/g)).toHaveLength(5);expect(sql.match(/create or replace function/g)).toHaveLength(4);expect(sql).toContain('create table if not exists public.billing_locks');expect(sql).toContain('grant select,update on public.profiles to service_role');expect(sql).toContain("notify pgrst, 'reload schema'");expect(sql).not.toMatch(/drop table|delete from public.profiles|drop column/i);});
});
