import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import type Stripe from 'stripe';
import {proActivationEmail} from '../src/lib/email/pro-activation';
import {cycleForPrice,billingCopy} from '../src/config/billing';
import {deliverProActivation,type ActivationContext,type EmailClaim,type EmailEventRepository} from '../src/lib/email/billing';
import {sendTransactionalEmail,smtpConfig,type EmailResult} from '../src/lib/email/server';
import {processBillingEvent} from '../src/lib/stripe/service';
import type {BillingRepository} from '../src/lib/stripe/repository';
vi.mock('server-only',()=>({}));
const mail={sendMail:vi.fn(),close:vi.fn()};
vi.mock('nodemailer',()=>({default:{createTransport:vi.fn(()=>mail)}}));
import nodemailer from 'nodemailer';
const prices={monthly:'price_month',annual:'price_year'};
const details={priceId:prices.monthly,periodEnd:'2027-01-15T12:00:00Z'};
const context:ActivationContext={userId:'account-id',subscriptionId:'sub_one',stripeEventId:'evt_one',livemode:true,prices};
function claim(subscription='one'):EmailClaim{return {id:'mail-'+subscription,recipient_email:'account@example.invalid',stripe_price_id:prices.monthly,subscription_current_period_end:details.periodEnd};}
function dependencies(){const claimed=new Set<string>();const repository:EmailEventRepository={claim:vi.fn(async ctx=>{if(claimed.has(ctx.subscriptionId))return null;claimed.add(ctx.subscriptionId);return claim(ctx.subscriptionId);}),finish:vi.fn(async()=>{})};return {repository,send:vi.fn(async()=>({status:'sent',code:'OK'} as EmailResult)),configured:()=>true};}
beforeEach(()=>{vi.clearAllMocks();mail.sendMail.mockResolvedValue({accepted:['account@example.invalid']});});
afterEach(()=>{vi.unstubAllEnvs();vi.restoreAllMocks();vi.useRealTimers();});
function smtp(){for(const [key,value]of Object.entries({SMTP_HOST:'smtp.ionos.de',SMTP_PORT:'465',SMTP_USER:'info@toolgrain.com',SMTP_PASSWORD:'secret-test-only',SMTP_FROM_EMAIL:'info@toolgrain.com',SMTP_FROM_NAME:'Toolgrain'}))vi.stubEnv(key,value);}
describe('branded activation message',()=>{
 it('monthly uses trusted EUR price labels',()=>{const email=proActivationEmail(details,prices)!;expect(email.text).toContain('Billing: Monthly');expect(email.text).toContain('€8.90 / month');expect(email.subject).toBe('Welcome to Toolgrain Pro');});
 it('annual uses trusted EUR price labels',()=>{const email=proActivationEmail({...details,priceId:prices.annual},prices)!;expect(email.text).toContain('Billing: Annual');expect(email.text).toContain('€69.00 / year');});
 it.each([['price_month','monthly'],['price_year','annual']])('selects cycle from trusted price %s', (price,cycle)=>expect(cycleForPrice(price,prices)).toBe(cycle));
 it('does not infer cycle from unknown price or identical config',()=>{expect(proActivationEmail({...details,priceId:'price_unknown'},prices)).toBeNull();expect(cycleForPrice('price_same',{monthly:'price_same',annual:'price_same'})).toBeNull();});
 it('uses actual UTC billing date clearly',()=>expect(proActivationEmail(details,prices)!.text).toContain('15 January 2027'));
 it('omits missing or invalid billing dates',()=>{for(const date of [null,'invalid'])expect(proActivationEmail({...details,periodEnd:date},prices)!.text).not.toContain('Next billing date');});
 it('contains HTTPS logo and account CTA',()=>{const email=proActivationEmail(details,prices)!;expect(email.html).toContain('https://toolgrain.com/brand/toolgrain-logo.png');expect(email.html).toContain('href="https://toolgrain.com/account"');expect(email.html).toContain('alt="Toolgrain"');});
 it('has useful text fallback and file privacy copy',()=>{const email=proActivationEmail(details,prices)!;expect(email.text).toContain('Your files still stay on your device.');expect(email.text).toContain('https://toolgrain.com/account');expect(email.text).toContain('Invoices and payment receipts are provided by Stripe.');});
 it('does not leak arbitrary tool payload properties',()=>{const email=proActivationEmail({...details,filename:'secret-file.csv',rows:['private-person'],payment:'secret-payment'} as typeof details,prices)!;expect(JSON.stringify(email)).not.toMatch(/secret-file|private-person|secret-payment/);});
 it('uses conservative responsive HTML',()=>{const html=proActivationEmail(details,prices)!.html;expect(html).toContain('max-width:600px');expect(html).toContain('width:100%');expect(html).toContain('background:#31674e');expect(html).not.toMatch(/<script|<link|@import|width="600"/i);});
 it('centralizes price labels from plan configuration',()=>{expect(billingCopy.monthly.priceLabel).toBe('€8.90 / month');expect(billingCopy.annual.priceLabel).toBe('€69.00 / year');});
});
describe('persistent activation dispatch',()=>{
 it('uses trusted account recipient, not external Stripe/browser email',async()=>{const deps=dependencies();await deliverProActivation({...context,email:'attacker@example.invalid'} as ActivationContext,deps);expect(deps.send).toHaveBeenCalledWith(expect.objectContaining({to:'account@example.invalid'}));});
 it('repeated event and distinct renewal event do not duplicate a subscription email',async()=>{const deps=dependencies();await deliverProActivation(context,deps);await deliverProActivation(context,deps);await deliverProActivation({...context,stripeEventId:'evt_renewal'},deps);expect(deps.send).toHaveBeenCalledTimes(1);});
 it('concurrent webhook calls result in one SMTP attempt',async()=>{const deps=dependencies();await Promise.all([deliverProActivation(context,deps),deliverProActivation(context,deps)]);expect(deps.send).toHaveBeenCalledTimes(1);});
 it('new subscription after cancellation can receive its own email',async()=>{const deps=dependencies();await deliverProActivation(context,deps);await deliverProActivation({...context,subscriptionId:'sub_two'},deps);expect(deps.send).toHaveBeenCalledTimes(2);});
 it('unknown price sends no misleading email',async()=>{const deps=dependencies();vi.mocked(deps.repository.claim).mockResolvedValue({...claim(),stripe_price_id:'unknown'});await deliverProActivation(context,deps);expect(deps.send).not.toHaveBeenCalled();expect(deps.repository.finish).toHaveBeenCalledWith('mail-one',{status:'failed',code:'UNKNOWN_PRICE'});});
 it('missing account email sends nothing',async()=>{const deps=dependencies();vi.mocked(deps.repository.claim).mockResolvedValue({...claim(),recipient_email:null});await deliverProActivation(context,deps);expect(deps.send).not.toHaveBeenCalled();});
 it('missing SMTP config leaves billing unaffected and claim pending',async()=>{const deps=dependencies();deps.configured=()=>false;await expect(deliverProActivation(context,deps)).resolves.toBeUndefined();expect(deps.repository.claim).not.toHaveBeenCalled();});
 it('SMTP failure is recorded without retrying the ambiguous send',async()=>{const deps=dependencies();deps.send.mockResolvedValue({status:'failed',code:'ETIMEDOUT'});await deliverProActivation(context,deps);await deliverProActivation(context,deps);expect(deps.send).toHaveBeenCalledTimes(1);expect(deps.repository.finish).toHaveBeenCalledWith('mail-sub_one',{status:'failed',code:'ETIMEDOUT'});});
 it('unexpected SMTP exceptions never expose raw text',async()=>{const deps=dependencies();deps.send.mockRejectedValue(new Error('secret password cookie CSV'));const log=vi.spyOn(console,'warn').mockImplementation(()=>{});await expect(deliverProActivation(context,deps)).resolves.toBeUndefined();expect(JSON.stringify(log.mock.calls)).not.toMatch(/secret|password|cookie|CSV/);});
 it('email database failure never fails successful billing',async()=>{const deps=dependencies();vi.mocked(deps.repository.claim).mockRejectedValue(new Error('secret DB token'));await expect(deliverProActivation(context,deps)).resolves.toBeUndefined();expect(deps.send).not.toHaveBeenCalled();});
 it('test subscription diagnostics are explicit without Sandbox email branding',async()=>{const deps=dependencies();const log=vi.spyOn(console,'warn').mockImplementation(()=>{});await deliverProActivation({...context,livemode:false},deps);expect(log).toHaveBeenCalledWith('Toolgrain billing email',expect.objectContaining({code:'TEST_SUBSCRIPTION_EMAIL_SENT',livemode:false}));expect(JSON.stringify(deps.send.mock.calls)).not.toContain('Sandbox');});
 it('migration queues complete rows and atomically claims once with service-only access',()=>{const sql=readFileSync('supabase/migrations/202610070002_billing_emails.sql','utf8');expect(sql).toContain('create table if not exists public.billing_email_events');expect(sql).toContain('unique(stripe_subscription_id,email_type)');expect(sql).not.toMatch(/old\.(?:plan|stripe_subscription_id)/i);expect(sql).toContain("if new.plan='pro' and new.stripe_subscription_id is not null and new.stripe_price_id is not null then");expect(sql).toContain("after update of plan,stripe_subscription_id,stripe_price_id,subscription_current_period_end on public.profiles");expect(sql).toContain("on conflict(stripe_subscription_id,email_type) do nothing");expect(sql).toContain("e.status='pending'");expect(sql).toContain("set status='sending'");expect(sql).toContain('left join auth.users');expect(sql).toContain('from public,anon,authenticated');expect(sql).toContain('to service_role');expect(sql).not.toMatch(/grant.*(?:authenticated|anon)/);});
});
describe('SMTP boundary',()=>{
 it('bounds the entire SMTP attempt and closes an unresponsive transport',async()=>{smtp();vi.useFakeTimers();mail.sendMail.mockImplementationOnce(()=>new Promise(()=>{}));const pending=sendTransactionalEmail({...proActivationEmail(details,prices)!,to:'account@example.invalid'});await vi.advanceTimersByTimeAsync(10000);expect(await pending).toEqual({status:'failed',code:'ETIMEDOUT'});expect(mail.close).toHaveBeenCalled();});
 it('transport construction failures are safely handled',async()=>{smtp();vi.mocked(nodemailer.createTransport).mockImplementationOnce(()=>{throw Object.assign(new Error('secret credentials'),{code:'EAUTH'});});expect(await sendTransactionalEmail({...proActivationEmail(details,prices)!,to:'account@example.invalid'})).toEqual({status:'failed',code:'EAUTH'});});
 it('configures IONOS TLS and Toolgrain sender with text fallback',async()=>{smtp();const email=proActivationEmail(details,prices)!;expect(await sendTransactionalEmail({...email,to:'account@example.invalid'})).toMatchObject({status:'sent'});expect(nodemailer.createTransport).toHaveBeenCalledWith(expect.objectContaining({host:'smtp.ionos.de',port:465,secure:true,logger:false,debug:false,socketTimeout:10000}));expect(mail.sendMail).toHaveBeenCalledWith(expect.objectContaining({from:{name:'Toolgrain',address:'info@toolgrain.com'},text:email.text}));expect(mail.close).toHaveBeenCalled();});
 it('STARTTLS required for other ports',async()=>{smtp();vi.stubEnv('SMTP_PORT','587');await sendTransactionalEmail({...proActivationEmail(details,prices)!,to:'account@example.invalid'});expect(nodemailer.createTransport).toHaveBeenCalledWith(expect.objectContaining({secure:false,requireTLS:true}));});
 it('missing SMTP does not construct transport',async()=>{vi.stubEnv('SMTP_PASSWORD','');expect(smtpConfig()).toBeNull();expect(await sendTransactionalEmail({...proActivationEmail(details,prices)!,to:'account@example.invalid'})).toMatchObject({status:'unavailable'});expect(nodemailer.createTransport).not.toHaveBeenCalled();});
 it('sanitizes SMTP errors and closes transport',async()=>{smtp();mail.sendMail.mockRejectedValue({code:'EAUTH',message:'secret password',response:'private credentials'});expect(await sendTransactionalEmail({...proActivationEmail(details,prices)!,to:'account@example.invalid'})).toEqual({status:'failed',code:'EAUTH'});expect(mail.close).toHaveBeenCalled();});
 it('rejects header injection before SMTP',async()=>{smtp();expect(await sendTransactionalEmail({...proActivationEmail(details,prices)!,to:'victim@example.invalid\r\nBcc:attacker@example.invalid'})).toMatchObject({status:'failed'});expect(mail.sendMail).not.toHaveBeenCalled();});
});
describe('webhook billing/email isolation',()=>{
 function setup(status='active',price=prices.monthly){const sub={id:'sub_one',customer:'cus_one',created:1,status,items:{data:[{quantity:1,price:{id:price},current_period_end:1800000000}]}} as unknown as Stripe.Subscription;const stripe={subscriptions:{list:()=>({[Symbol.asyncIterator]:async function*(){yield sub;}}),retrieve:async()=>sub}} as unknown as Stripe;const repo={lock:async()=> 'token',release:vi.fn(),userForCustomer:async()=>context.userId,write:vi.fn(async()=>{})} as unknown as BillingRepository;const event={id:'evt_one',livemode:true,type:'customer.subscription.updated',data:{object:{customer:'cus_one',email:'attacker@example.invalid',csv:'private'}}} as unknown as Stripe.Event;return {stripe,repo,event};}
 it('only calls email after successful Pro write, ignoring arbitrary payload data',async()=>{const {stripe,repo,event}=setup();const notify=vi.fn(async()=>{expect(repo.write).toHaveBeenCalledWith(context.userId,'token','cus_one',expect.objectContaining({plan:'pro'}));});await processBillingEvent(stripe,repo,event,prices,notify);expect(notify).toHaveBeenCalledWith(context);expect(JSON.stringify(notify.mock.calls)).not.toMatch(/attacker|private/);});
 it('SMTP failure cannot downgrade or corrupt Pro state',async()=>{const {stripe,repo,event}=setup();await expect(processBillingEvent(stripe,repo,event,prices,async()=>{throw new Error('SMTP unavailable');})).resolves.toBeUndefined();expect(repo.write).toHaveBeenCalledTimes(1);expect(repo.write).toHaveBeenCalledWith(context.userId,'token','cus_one',expect.objectContaining({plan:'pro',stripe_subscription_id:'sub_one'}));expect(repo.release).toHaveBeenCalled();});
 it('failed entitlement write never attempts email',async()=>{const {stripe,repo,event}=setup();vi.mocked(repo.write).mockRejectedValue(new Error('DB unavailable'));const notify=vi.fn();await expect(processBillingEvent(stripe,repo,event,prices,notify)).rejects.toThrow();expect(notify).not.toHaveBeenCalled();});
 it.each([['canceled',prices.monthly],['active','price_unknown']])('non-entitled %s / %s sends no welcome',async(status,price)=>{const {stripe,repo,event}=setup(status,price);const notify=vi.fn();await processBillingEvent(stripe,repo,event,prices,notify);expect(notify).not.toHaveBeenCalled();});
});
