import { describe, expect, it, vi } from 'vitest';
import Papa from 'papaparse';
import { analyzeCrm } from '../src/lib/crm/analyze-crm';
import { detectColumns } from '../src/lib/csv/detect-columns';
import { parseCsvText } from '../src/lib/csv/parse-csv';
import { applySafeFixes,createCleaningSession,undoSafeFixes,resetChanges } from '../src/lib/crm/clean/apply-fixes';
import { decideDuplicate,unreviewDuplicate } from '../src/lib/crm/clean/duplicate-decisions';
import { exportCleanedCsv,cleanedFilename,downloadCleanedCsv } from '../src/lib/crm/clean/export-csv';
import { referenceRows } from './fixtures/reference-crm';
import type { ParsedCsv } from '../src/lib/csv/types';
function session(rows:Record<string,string>[],delimiter=','){const csv:ParsedCsv={columns:Object.keys(rows[0]).map(key=>({key,name:key})),rows,delimiter,warnings:[]};return createCleaningSession(csv,analyzeCrm(csv,detectColumns(csv.columns)))}
const original=()=>session(referenceRows);
describe('Local cleaning decisions and CSV export',()=>{
 it('triggers a browser download with a UTF-8 Blob and releases the URL',async()=>{
  vi.useFakeTimers();const click=vi.fn(),remove=vi.fn(),append=vi.fn();const link={href:'',download:'',click,remove};let captured:Blob|undefined;
  const create=vi.spyOn(URL,'createObjectURL').mockImplementation(blob=>{captured=blob as Blob;return 'blob:local-test'});const revoke=vi.spyOn(URL,'revokeObjectURL').mockImplementation(()=>{});
  vi.stubGlobal('document',{createElement:()=>link,body:{append}});
  try{downloadCleanedCsv(original(),'customers.csv');expect(link.download).toBe('customers-cleaned.csv');expect(link.href).toBe('blob:local-test');expect(append).toHaveBeenCalledWith(link);expect(click).toHaveBeenCalledOnce();expect(remove).toHaveBeenCalledOnce();expect(captured?.type).toBe('text/csv;charset=utf-8');expect(await captured?.text()).toBe(exportCleanedCsv(original()).replace(/^\uFEFF/,''));expect([...new Uint8Array(await captured!.arrayBuffer()).slice(0,3)]).toEqual([239,187,191]);vi.runAllTimers();expect(revoke).toHaveBeenCalledWith('blob:local-test')}finally{create.mockRestore();revoke.mockRestore();vi.unstubAllGlobals();vi.useRealTimers()}
 });
 it('applies only available fixes when rows were excluded before fixing',()=>{const start=original(),id=start.analysis.duplicateGroups[0].id;const kept=decideDuplicate(start,id,{kind:'keep_row',row:1});const applied=applySafeFixes(kept);expect(applied.appliedFixes).toHaveLength(2);expect(applySafeFixes(applied).appliedFixes).toHaveLength(2);const restored=decideDuplicate(applied,id,{kind:'keep_all'});expect(applySafeFixes(restored).appliedFixes).toHaveLength(4)});
 it('lowercases a valid email from its analyzer suggestion',()=>{const next=applySafeFixes(session([{email:'ANNA@EXAMPLE.COM'}]));expect(next.workingRows[0].email).toBe('anna@example.com');expect(next.appliedFixes).toHaveLength(1)});
 it('applies only conservative analyzer name suggestions',()=>{const next=applySafeFixes(session([{first_name:'anna',last_name:'müller'},{first_name:'McDonald',last_name:"O'Neill"}]));expect(next.workingRows[0]).toEqual({first_name:'Anna',last_name:'Müller'});expect(next.workingRows[1]).toEqual({first_name:'McDonald',last_name:"O'Neill"})});
 it('never auto-corrects an invalid uppercase email',()=>{const next=applySafeFixes(session([{email:'BAD@@EXAMPLE.COM'}]));expect(next.workingRows[0].email).toBe('BAD@@EXAMPLE.COM');expect(next.appliedFixes).toHaveLength(0);expect(next.unresolvedIssues[0].type).toBe('invalid_email')});
 it('never auto-fills blank or whitespace missing values',()=>{const row={company:'',location:' ',phone:'',email:''};expect(applySafeFixes(session([row])).workingRows[0]).toEqual(row)});
 it('never normalizes phone presentation',()=>{const next=applySafeFixes(session([{phone:'+49 (211) 555-0198'},{phone:'+492115550199'}]));expect(next.workingRows.map(row=>row.phone)).toEqual(['+49 (211) 555-0198','+492115550199'])});
 it('explicit keep all preserves every duplicate row and marks reviewed',()=>{const start=original(),group=start.analysis.duplicateGroups[0];const next=decideDuplicate(start,group.id,{kind:'keep_all'});expect(next.workingRows).toHaveLength(20);expect(next.removedRows).toEqual([]);expect(next.duplicateDecisions[group.id].kind).toBe('keep_all')});
 it('keep row excludes only the other rows in its group',()=>{const start=original(),next=decideDuplicate(start,start.analysis.duplicateGroups[0].id,{kind:'keep_row',row:2});expect(next.workingRows).toHaveLength(19);expect(next.removedRows).toEqual([1]);expect(next.retainedRowNumbers).toContain(2);expect(start.workingRows).toHaveLength(20)});
 it('unreviewed exact and likely groups retain all rows by default',()=>{const next=original();expect(next.duplicateDecisions).toEqual({});expect(next.workingRows).toHaveLength(20);expect(next.retainedRowNumbers).toContain(17);expect(next.retainedRowNumbers).toContain(18)});
 it('freezes independent originals and never mutates input',()=>{const rows=referenceRows.map(row=>Object.freeze({...row}));const before=JSON.stringify(rows);const start=session(rows),next=applySafeFixes(start);next.workingRows[0].email='edited working copy';expect(JSON.stringify(rows)).toBe(before);expect(start.originalCsv.rows[0].email).toBe('ANNA.MUELLER@EXAMPLE.COM');expect(Object.isFrozen(start.originalCsv.rows[0])).toBe(true);expect(Object.isFrozen(start.originalCsv.rows)).toBe(true)});
 it('reset restores all originals, fixes and duplicate decisions',()=>{const start=original();const changed=decideDuplicate(applySafeFixes(start),start.analysis.duplicateGroups[0].id,{kind:'keep_row',row:1});const reset=resetChanges(changed);expect(reset.workingRows).toEqual(start.originalCsv.rows);expect(reset.appliedFixes).toEqual([]);expect(reset.duplicateDecisions).toEqual({});expect(reset.removedRows).toEqual([]);expect(reset.unresolvedIssues).toEqual(start.analysis.issues)});
 it('undo safe fixes preserves explicit duplicate decisions',()=>{const start=original();const changed=decideDuplicate(applySafeFixes(start),start.analysis.duplicateGroups[0].id,{kind:'keep_row',row:1});const undo=undoSafeFixes(changed);expect(undo.workingRows[0].email).toBe('ANNA.MUELLER@EXAMPLE.COM');expect(undo.removedRows).toEqual([2]);expect(undo.appliedFixes).toEqual([])});
 it('export retains original header order',()=>{const text=exportCleanedCsv(session([{notes:'n',email:'a@example.com',company:'A'}]));expect(Papa.parse<string[]>(text).data[0]).toEqual(['notes','email','company'])});
 it('export contains no analyzer keys or issue metadata',()=>{const next=applySafeFixes(original());const parsed=Papa.parse<string[]>(exportCleanedCsv(next));expect(parsed.data[0]).toEqual(['first_name','last_name','company','email','phone','location']);expect(parsed.data.every(row=>row.length===6)).toBe(true)});
 it.each([',',';'])('roundtrips quotes, commas, semicolons, newlines and blank cells with %s',delimiter=>{const start=session([{notes:'quoted "value", x; y\nsecond line',email:'a@example.com',company:''}],delimiter);const roundtrip=parseCsvText(exportCleanedCsv(start));expect(roundtrip.delimiter).toBe(delimiter);expect(Object.values(roundtrip.rows[0])).toEqual(Object.values(start.workingRows[0]))});
 it('Unicode and original strings survive UTF-8 export',()=>{const next=session([{first_name:'Müller',notes:'ä ö ü ß é 東京 🙂',id:'001',space:'  unchanged  '}]);const encoded=new TextEncoder().encode(exportCleanedCsv(next));const decoded=new TextDecoder().decode(encoded);expect(Papa.parse<string[]>(decoded).data[1]).toEqual(Object.values(next.workingRows[0]))});
 it.each([['customers.csv','customers-cleaned.csv'],['crm_export.csv','crm_export-cleaned.csv'],['C:\\fakepath\\Müller.CSV','Müller-cleaned.csv'],['../bad:name.csv','bad_name-cleaned.csv'],['.csv','contacts-cleaned.csv']])('names %s safely',(input,expected)=>expect(cleanedFilename(input)).toBe(expected));
 it('safe fixes leave unrelated cells and original whitespace alone',()=>{const row={email:'A@EXAMPLE.COM',notes:'  ORIGINAL  ',phone:'0012345678',company:'ACME'};const next=applySafeFixes(session([row]));expect(next.workingRows[0]).toEqual({...row,email:'a@example.com'});expect(next.originalCsv.rows[0]).toEqual(row)});
 it('cleans and exports 10,000 rows in bounded time',()=>{const started=performance.now();const start=session(Array.from({length:10000},(_,i)=>({id:String(i),email:'PERSON'+i+'@EXAMPLE.COM',first_name:'anna'})));const next=applySafeFixes(start);const text=exportCleanedCsv(next);expect(next.appliedFixes).toHaveLength(20000);expect(Papa.parse<string[]>(text).data).toHaveLength(10001);expect(next.originalCsv.rows[9999].email).toBe('PERSON9999@EXAMPLE.COM');expect(performance.now()-started).toBeLessThan(5000)});
 it('does not delete exact duplicates when safe fixes are applied',()=>{const next=applySafeFixes(original());expect(next.workingRows).toHaveLength(20);expect(next.removedRows).toEqual([])});
 it('can reverse a row decision back to keep all or unreviewed',()=>{const start=original(),id=start.analysis.duplicateGroups[0].id;const kept=decideDuplicate(start,id,{kind:'keep_row',row:1});expect(decideDuplicate(kept,id,{kind:'keep_all'}).workingRows).toHaveLength(20);expect(unreviewDuplicate(kept,id).duplicateDecisions).toEqual({})});
 it('rejects an unrelated row choice and unknown group',()=>{const start=original();expect(()=>decideDuplicate(start,start.analysis.duplicateGroups[0].id,{kind:'keep_row',row:20})).toThrow();expect(()=>decideDuplicate(start,'unknown',{kind:'keep_all'})).toThrow()});
 it('keeps duplicate header columns separate when applying a fix',()=>{const csv=parseCsvText('email,email,notes\nUPPER@EXAMPLE.COM,other@example.com,untouched');const next=applySafeFixes(createCleaningSession(csv,analyzeCrm(csv,detectColumns(csv.columns))));expect(Papa.parse<string[]>(exportCleanedCsv(next)).data).toEqual([['email','email','notes'],['upper@example.com','other@example.com','untouched']])});
 it('counts remaining findings on retained rows and reviewed groups',()=>{const start=original(),applied=applySafeFixes(start);expect(applied.unresolvedIssues).toHaveLength(15);const next=decideDuplicate(applied,start.analysis.duplicateGroups[0].id,{kind:'keep_row',row:1});expect(next.unresolvedIssues.filter(issue=>issue.duplicateGroupId===start.analysis.duplicateGroups[0].id)).toHaveLength(0);expect(next.unresolvedIssues.filter(issue=>issue.type==='invalid_email')).toHaveLength(2)});
 it('new sessions contain no previous choices or fixes',()=>{const old=applySafeFixes(original());const fresh=session([{email:'new@example.com'}]);expect(old.appliedFixes.length).toBeGreaterThan(0);expect(fresh.appliedFixes).toEqual([]);expect(fresh.duplicateDecisions).toEqual({});expect(fresh.workingRows).toEqual([{email:'new@example.com'}])});
});
