import { describe, expect, it } from 'vitest';
import { parseCsvText } from '../src/lib/csv/parse-csv';
import { detectColumns } from '../src/lib/csv/detect-columns';
import { analyzeCrm } from '../src/lib/crm/analyze-crm';
import { duplicateMatchReasons } from '../src/lib/crm/types';
import { createCleaningSession } from '../src/lib/crm/clean/apply-fixes';
import { decideDuplicate } from '../src/lib/crm/clean/duplicate-decisions';
import { exportCleanedCsv } from '../src/lib/crm/clean/export-csv';
function analyze(text:string,column?:string) {const csv=parseCsvText(text);const key=csv.columns.find(c=>c.name===column)?.key;return {csv,analysis:analyzeCrm(csv,detectColumns(csv.columns),{customKeyColumn:key})};}
function source(a:string,b:string) {return 'customer_id,label\n'+a+',First\n'+b+',Second';}
describe('CRM optional custom duplicate key',()=>{
 it('same non-empty key creates a group',()=>{const {analysis}=analyze(source('224345040','224345040'),'customer_id');expect(analysis.duplicateGroups[0].rows).toEqual([1,2]);expect(analysis.duplicateGroups[0].kind).toBe('likely');});
 it('trims custom keys',()=>{expect(analyze(source(' 224345040 ','224345040'),'customer_id').analysis.duplicateGroups).toHaveLength(1);});
 it('keeps case significant',()=>{expect(analyze(source('ABC','abc'),'customer_id').analysis.duplicateGroups).toHaveLength(0);});
 it('keeps suffixes significant',()=>{expect(analyze(source('224322318','224322318-1'),'customer_id').analysis.duplicateGroups).toHaveLength(0);});
 it('ignores empty values',()=>{expect(analyze(source('',''),'customer_id').analysis.duplicateGroups).toHaveLength(0);});
 it('ignores whitespace-only values',()=>{expect(analyze(source('  ',' '),'customer_id').analysis.duplicateGroups).toHaveLength(0);});
 it('reports selected header and matching value clearly',()=>{const {analysis}=analyze(source('123 ','123'),'customer_id');const match=analysis.duplicateGroups[0].matches[0];expect(match.customKey).toMatchObject({columnName:'customer_id',value:'123'});expect(duplicateMatchReasons(match)).toEqual(['Same value in selected duplicate key column "customer_id". Value: 123']);});
 it('merges with email-linked groups transitively without overlap',()=>{const {analysis}=analyze('customer_id,email,label\nA,same@example.com,First\nB,same@example.com,Second\nB,other@example.com,Third','customer_id');expect(analysis.duplicateGroups).toHaveLength(1);expect(analysis.duplicateGroups[0].rows).toEqual([1,2,3]);expect(analysis.duplicateGroups[0].matches.map(m=>m.rows)).toEqual([[1,2],[2,3]]);});
 it('keeps exact classification and adds the custom reason to the same pair',()=>{const {analysis}=analyze('customer_id,label\n123,Same\n123,Same','customer_id');expect(analysis.duplicateGroups).toHaveLength(1);expect(analysis.duplicateGroups[0].kind).toBe('exact');expect(analysis.duplicateGroups[0].matches).toHaveLength(1);expect(analysis.duplicateGroups[0].matches[0].reasons).toEqual(['exact_values','custom_key']);expect(analysis.counts.exact_duplicate).toBe(1);expect(analysis.counts.likely_duplicate).toBe(0);});
 it('changing selected key changes results',()=>{const text='customer_id,reference,label\n1,A,First\n1,B,Second';expect(analyze(text,'customer_id').analysis.duplicateGroups).toHaveLength(1);expect(analyze(text,'reference').analysis.duplicateGroups).toHaveLength(0);});
 it('does not modify frozen original values',()=>{const {csv}=analyze(source(' 123 ','123'));csv.rows.forEach(Object.freeze);const original=JSON.stringify(csv);analyzeCrm(csv,detectColumns(csv.columns),{customKeyColumn:'column_0'});expect(JSON.stringify(csv)).toBe(original);});
 it('disabled configuration preserves the previous automatic analysis exactly',()=>{const csv=parseCsvText('customer_id,email,label\n1,a@example.com,First\n2,A@example.com,Second\n1,b@example.com,Third');const detected=detectColumns(csv.columns);expect(analyzeCrm(csv,detected,{})).toEqual(analyzeCrm(csv,detected));expect(analyzeCrm(csv,detected,{customKeyColumn:undefined})).toEqual(analyzeCrm(csv,detected));});
 it('handles 10,000 rows with custom keys without all-pairs matching',()=>{const csv=parseCsvText('customer_id,label\n'+Array.from({length:10000},(_,i)=>Math.floor(i/2)+',Row '+i).join('\n'));const start=performance.now();const analysis=analyzeCrm(csv,detectColumns(csv.columns),{customKeyColumn:'column_0'});expect(analysis.duplicateGroups).toHaveLength(5000);expect(analysis.duplicateGroups.every(g=>g.rows.length===2&&g.kind==='likely')).toBe(true);expect(performance.now()-start).toBeLessThan(5000);});
 it('keeps all custom duplicates until a user decision',()=>{const {csv,analysis}=analyze(source(' 123 ','123'),'customer_id');const session=createCleaningSession(csv,analysis);expect(session.workingRows).toHaveLength(2);expect(session.removedRows).toEqual([]);expect(parseCsvText(exportCleanedCsv(session)).rows[0].column_0).toBe(' 123 ');const chosen=decideDuplicate(session,analysis.duplicateGroups[0].id,{kind:'keep_row',row:2});expect(chosen.removedRows).toEqual([1]);expect(parseCsvText(exportCleanedCsv(chosen)).rows).toHaveLength(1);expect(session.originalCsv.rows).toHaveLength(2);});
 it('a fresh analysis resets prior cleaning decisions and retains all rows',()=>{const {csv,analysis}=analyze(source('1','1'),'customer_id');const chosen=decideDuplicate(createCleaningSession(csv,analysis),analysis.duplicateGroups[0].id,{kind:'keep_row',row:1});expect(chosen.removedRows).toHaveLength(1);const fresh=createCleaningSession(csv,analyzeCrm(csv,detectColumns(csv.columns)));expect(fresh.duplicateDecisions).toEqual({});expect(fresh.workingRows).toHaveLength(2);});
 it('does not weaken email matching when custom values differ',()=>{const {analysis}=analyze('customer_id,email\nABC,a@example.com\nabc,A@example.com','customer_id');expect(analysis.duplicateGroups).toHaveLength(1);expect(analysis.duplicateGroups[0].matches[0].reasons).toEqual(['email']);});
 it('preserves exact subgroups inside a custom-key connected group',()=>{const {analysis}=analyze('customer_id,label\n1,A\n1,A\n1,B','customer_id');expect(analysis.duplicateGroups).toHaveLength(1);expect(analysis.duplicateGroups[0].exactSubgroups).toEqual([[1,2]]);expect(analysis.duplicateGroups[0].kind).toBe('likely');});
 it('does not coerce leading zeros or punctuation',()=>{expect(analyze(source('001','1'),'customer_id').analysis.duplicateGroups).toHaveLength(0);expect(analyze(source('A-B','AB'),'customer_id').analysis.duplicateGroups).toHaveLength(0);});
 it('keeps a single 10,000-member custom group linear in pair count',()=>{const csv=parseCsvText('key,label\n'+Array.from({length:10000},(_,i)=>'same,Row '+i).join('\n'));const a=analyzeCrm(csv,detectColumns(csv.columns),{customKeyColumn:'column_0'});expect(a.duplicateGroups).toHaveLength(1);expect(a.duplicateGroups[0].matches).toHaveLength(9999);});
 it('rejects a nonexistent custom column',()=>{const {csv}=analyze(source('1','1'));expect(()=>analyzeCrm(csv,detectColumns(csv.columns),{customKeyColumn:'bad'})).toThrow('Choose a valid');});
});
