import {describe,it,expect,vi} from 'vitest';
import {generateTicketReference} from '../src/lib/feedback/generate-ticket-reference';
import {createFeedbackContext,type FeedbackInput} from '../src/lib/feedback/context';
import {createFeedbackMailto} from '../src/lib/feedback/mailto';
describe('feedback references and mail transport',()=>{
 it('uses readable reference format and UTC date',()=>{expect(generateTicketReference(new Date('2026-10-06T12:00:00Z'),new Uint8Array([0,1,2,3]))).toBe('TG-20261006-ABCD');});
 it('repeated actions produce valid references',()=>{for(let n=0;n<100;n++)expect(generateTicketReference()).toMatch(/^TG-\d{8}-[A-HJ-NP-Z2-9]{4}$/);});
 it('uses central recipient, reference and tool name in subject',()=>{const c=createFeedbackContext({pagePath:'/tools/csv-compare',toolName:'CSV Compare'}),u=new URL(createFeedbackMailto(c));expect(u.pathname).toBe('info@toolgrain.com');expect(u.searchParams.get('subject')).toBe('['+c.ticketReference+'] Feedback – CSV Compare');expect(u.searchParams.get('body')).toContain('Tool: CSV Compare');});
 it('uses full production URL, line breaks and matching reference in body',()=>{const c=createFeedbackContext({pagePath:'/tools/crm-csv-cleaner',toolName:'CRM CSV Cleaner'}),body=new URL(createFeedbackMailto(c)).searchParams.get('body');expect(body).toContain('Ticket reference: '+c.ticketReference+'\nPage: https://toolgrain.com/tools/crm-csv-cleaner\nTool: CRM CSV Cleaner');});
 it('encodes umlauts and special characters safely',()=>{const u=new URL(createFeedbackMailto(createFeedbackContext({pagePath:'/about',pageTitle:'München & Tools?'})));expect(u.searchParams.get('subject')).toContain('München & Tools?');expect([...u.searchParams.keys()]).toEqual(['subject','body']);});
 it('generic page falls back to Toolgrain without a Tool line',()=>{const c=createFeedbackContext({pagePath:'/'});expect(c.pageTitle).toBe('Toolgrain');expect(new URL(createFeedbackMailto(c)).searchParams.get('body')).not.toContain('Tool:');});
 it('drops query strings, hashes and external/preview origins',()=>{for(const path of ['https://localhost:3000/private','//preview.vercel.app/x'])expect(createFeedbackContext({pagePath:path}).pageUrl).toBe('https://toolgrain.com/');expect(createFeedbackContext({pagePath:'/tools?filename=private.csv#rows'}).pageUrl).toBe('https://toolgrain.com/tools');});
 it('includes only explicitly supported context, not file/user data',()=>{const input={pagePath:'/tools',csv:'SECRET_CSV',filename:'SECRET_FILE',ip:'SECRET_IP'} as FeedbackInput;const mail=createFeedbackMailto(createFeedbackContext(input));expect(mail).not.toContain('SECRET');expect(createFeedbackContext(input)).not.toHaveProperty('csv');});
 it('allows explicitly supplied context for future callers',()=>expect(new URL(createFeedbackMailto(createFeedbackContext({pagePath:'/about',context:'Product idea'}))).searchParams.get('body')).toContain('Context: Product idea'));
 it('does not use browser storage or network',()=>{const fail=vi.fn(()=>{throw Error('Unexpected persistence or transmission');});vi.stubGlobal('localStorage',{getItem:fail,setItem:fail});vi.stubGlobal('sessionStorage',{getItem:fail,setItem:fail});vi.stubGlobal('fetch',fail);vi.stubGlobal('document',{get cookie(){return fail();},set cookie(_value){fail();}});try{createFeedbackMailto(createFeedbackContext({pagePath:'/about'}));expect(fail).not.toHaveBeenCalled();}finally{vi.unstubAllGlobals();}});
});
