import {analyzeCrm} from '../src/lib/crm/analyze-crm';
import {detectColumns} from '../src/lib/csv/detect-columns';
import {createCleaningSession} from '../src/lib/crm/clean/apply-fixes';
import {exportCleanedCsv} from '../src/lib/crm/clean/export-csv';
import {describe,it,expect} from 'vitest';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {plans,planTools,formatPlanPrice,type PlanToolId} from '../src/config/plans';
import {getCurrentPlan,getToolLimit,canProcessRows,canProcessFileSize,canCompareFiles,rowViolation,fileSizeViolation,fileSizeLimitMessage} from '../src/lib/entitlements';
import {UpgradePrompt,PlanIndicator} from '../src/components/tools/upgrade-prompt';
import {PricingContent} from '../src/components/pricing/pricing-content';
import {pricingMetadata} from '../src/config/pricing-metadata';
import {tools} from '../src/lib/tools';
import sitemap from '../src/app/sitemap';
import {siteConfig} from '../src/config/site';
import {parseCsvText} from '../src/lib/csv/parse-csv';
import {transformSupplier} from '../src/lib/shopify/transform';
import {suggestMappings} from '../src/lib/shopify/mapping';
import {canExport} from '../src/lib/shopify/validate';
import {exportShopifyCsv} from '../src/lib/shopify/export';
import {compareCsv} from '../src/lib/csv-compare/compare-csv';
describe('central plans and entitlements',()=>{
 it.each([['crm-csv-cleaner',500,true],['crm-csv-cleaner',501,false],['csv-compare',500,true],['csv-compare',501,false],['supplier-csv-to-shopify',100,true],['supplier-csv-to-shopify',101,false]] as const)('Free %s with %s rows allows %s',(tool,rows,allowed)=>expect(canProcessRows('free',tool,rows)).toBe(allowed));
 it.each([['crm-csv-cleaner',50000],['csv-compare',50000],['supplier-csv-to-shopify',10000]] as const)('Pro %s inclusive boundary %s',(tool,rows)=>{expect(canProcessRows('pro',tool,rows)).toBe(true);expect(canProcessRows('pro',tool,rows+1)).toBe(false);});
 it('allows Compare 500 + 500 and blocks either over-limit file',()=>{expect(canCompareFiles('free',500,500)).toBe(true);expect(canCompareFiles('free',501,500)).toBe(false);expect(canCompareFiles('free',500,501)).toBe(false);});
 it('gets every tool limit from central configuration',()=>{for(const tool of Object.keys(planTools) as PlanToolId[])for(const plan of ['free','pro'] as const)expect(getToolLimit(plan,tool)).toBe(plans[plan].limits[tool]);});
 it.each(['free','pro'] as const)('%s file limit uses inclusive byte convention',plan=>{const limit=plans[plan].fileSizeBytes;expect(canProcessFileSize(plan,limit)).toBe(true);expect(canProcessFileSize(plan,limit+1)).toBe(false);});
 it('central file size limits are 10 and 25 MiB',()=>{expect(plans.free.fileSizeBytes).toBe(10*1024*1024);expect(plans.pro.fileSizeBytes).toBe(25*1024*1024);});
 it('returns Free independently of production environment and browser state',()=>{expect(getCurrentPlan()).toBe('free');expect(getCurrentPlan()).toBe('free');});
 it('allows zero rows and rejects invalid usage counts',()=>{expect(canProcessRows('free','crm-csv-cleaner',0)).toBe(true);expect(canProcessRows('free','crm-csv-cleaner',-1)).toBe(false);expect(canProcessRows('free','crm-csv-cleaner',0.5)).toBe(false);expect(canProcessFileSize('free',Infinity)).toBe(false);});
 it('passes actual usage and limits into the reusable upgrade UI',()=>{const usage=rowViolation('free','crm-csv-cleaner',4823,'contacts.csv')!;expect(usage).toMatchObject({actual:4823,limit:500,proLimit:50000,exceedsPro:false});const html=renderToStaticMarkup(createElement(UpgradePrompt,{usage}));expect(html).toContain('4,823 contacts');expect(html).toContain('500 contacts');expect(html).toContain('50,000 contacts');expect(html).toContain('href="/pricing"');expect(html).toContain('purchases are not available');});
 it('identifies the over-limit Compare file',()=>expect(rowViolation('free','csv-compare',501,'New CSV: new.csv')?.label).toBe('New CSV: new.csv'));
 it('distinguishes plan file limit from maximum supported limit',()=>{expect(fileSizeViolation('free','csv-compare',plans.free.fileSizeBytes+1,'old.csv')?.exceedsPro).toBe(false);expect(fileSizeViolation('free','csv-compare',plans.pro.fileSizeBytes+1,'old.csv')?.exceedsPro).toBe(true);expect(fileSizeLimitMessage('free',plans.pro.fileSizeBytes+1)).toContain('maximum supported');expect(fileSizeLimitMessage('free',plans.free.fileSizeBytes+1)).toContain('Free plan');});
 it('never implies Pro can process files above its own limit',()=>{const usage=rowViolation('free','supplier-csv-to-shopify',10001)!;const html=renderToStaticMarkup(createElement(UpgradePrompt,{usage}));expect(html).toContain('also exceeds the planned Pro limit');});
 it('indicators reflect central limits before selecting a file',()=>{const html=renderToStaticMarkup(createElement(PlanIndicator,{tool:'csv-compare'}));expect(html).toContain('Free plan');expect(html).toContain('500');expect(html).toContain('rows per file');expect(html).toContain('10 MB');});
 it('prices are accurate and pricing does not offer checkout',()=>{const html=renderToStaticMarkup(createElement(PricingContent));expect(formatPlanPrice(plans.pro.monthlyPrice)).toBe('€8.90');expect(formatPlanPrice(plans.pro.annualPrice)).toBe('€69.00');expect(html).toContain('€8.90');expect(html).toContain('€69.00');expect(html).toContain('Pro coming soon');expect(html).toContain('disabled=""');expect(html).not.toContain('checkout');expect(html).not.toContain('unlimited');});
 it('all plan tool IDs correspond to available central registry tools',()=>{for(const tool of Object.keys(planTools))expect(tools.find(t=>t.slug===tool)?.status).toBe('available');});
 it('pricing metadata uses the production canonical and exact title',()=>{expect(pricingMetadata.title).toEqual({absolute:'Toolgrain Pricing – Free & Pro'});expect(pricingMetadata.alternates?.canonical).toBe('https://toolgrain.com/pricing');expect(pricingMetadata.description).toBe('Use Toolgrain for free on smaller files or upgrade to Pro for larger CSVs and product catalogs across every Toolgrain tool.');});
 it('pricing is discoverable through navigation and sitemap',()=>{expect(sitemap().some(e=>e.url==='https://toolgrain.com/pricing')).toBe(true);expect(siteConfig.navigation.map(n=>n.label)).toEqual(['Tools','Pricing','About']);});
 it('small Free supplier data remains immutable and fully exportable',()=>{const csv=parseCsvText('title,sku\nMünchen,001');const before=JSON.stringify(csv);expect(canProcessRows(getCurrentPlan(),'supplier-csv-to-shopify',csv.rows.length)).toBe(true);const result=transformSupplier(csv,suggestMappings(csv.columns));expect(canExport(result)).toBe(true);expect(exportShopifyCsv(result,'x.csv').csv).toContain('München');expect(JSON.stringify(csv)).toBe(before);});
 it('small Free Compare remains complete',()=>{const a=parseCsvText('id,value\n1,A'),b=parseCsvText('id,value\n1,B');expect(canCompareFiles(getCurrentPlan(),a.rows.length,b.rows.length)).toBe(true);const result=compareCsv(a,b,a.columns[0].key,b.columns[0].key);expect(result.changed.length).toBe(1);});
});

it('small Free CRM keeps its complete local export and source values',()=>{const csv=parseCsvText('email,first_name,last_name\ncontact@example.com,Müller,Test');const before=JSON.stringify(csv);expect(canProcessRows(getCurrentPlan(),'crm-csv-cleaner',csv.rows.length)).toBe(true);const health=analyzeCrm(csv,detectColumns(csv.columns));const session=createCleaningSession(csv,health);expect(exportCleanedCsv(session)).toContain('Müller');expect(JSON.stringify(csv)).toBe(before);});
