import {billingCopy,cycleForPrice} from '@/config/billing';
import {siteConfig} from '@/config/site';
export type ActivationDetails={priceId:string;periodEnd:string|null};
function escapeHtml(value:string){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));}
export function proActivationEmail(details:ActivationDetails,prices:{monthly:string;annual:string}){
 const cycle=cycleForPrice(details.priceId,prices);if(!cycle)return null;
 const copy=billingCopy[cycle];const date=details.periodEnd?new Date(details.periodEnd):null;
 const next=date&&Number.isFinite(date.getTime())?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(date):null;
 const account=siteConfig.url+'/account';
 const text=['Toolgrain Pro is active','Your subscription is ready to use.','Plan: Toolgrain Pro','Billing: '+copy.cycle,'Price: '+copy.priceLabel,...(next?['Next billing date: '+next]:[]),'Manage your account: '+account,'Your files still stay on your device. Pro unlocks larger local processing limits.','Invoices and payment receipts are provided by Stripe.','Toolgrain','One task. One tool. Done.','toolgrain.com'].join('\n\n');
 const html=`<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width, initial-scale=1"><meta charset="utf-8"><title>Toolgrain Pro is active</title></head><body style="margin:0;padding:24px 12px;background:#f7f8f5;color:#202c29;font-family:Arial,Helvetica,sans-serif;line-height:1.6"><table role="presentation" style="width:100%;max-width:600px;margin:0 auto;border-collapse:collapse"><tr><td style="padding:24px;background:#ffffff;border:1px solid #e5e9e5;border-radius:12px"><img src="https://toolgrain.com/brand/toolgrain-logo.png" alt="Toolgrain" width="180" style="display:block;width:180px;max-width:100%;height:auto;margin-bottom:28px"><h1 style="font-size:26px;line-height:1.25;margin:0 0 16px">Toolgrain Pro is active</h1><p>Your subscription is ready to use.</p><p><strong>Plan:</strong> Toolgrain Pro<br><strong>Billing:</strong> ${copy.cycle}<br><strong>Price:</strong> ${escapeHtml(copy.priceLabel)}${next?'<br><strong>Next billing date:</strong> '+escapeHtml(next):''}</p><p style="margin:28px 0"><a href="${account}" style="display:inline-block;padding:14px 22px;border-radius:7px;background:#31674e;color:#ffffff;text-decoration:none;font-weight:bold">Manage your account</a></p><p>Your files still stay on your device. Pro unlocks larger local processing limits.</p><p style="font-size:13px;color:#737b77">Invoices and payment receipts are provided by Stripe.</p></td></tr><tr><td style="padding:20px 12px;text-align:center;font-size:13px;color:#737b77">Toolgrain<br>One task. One tool. Done.<br><a href="${siteConfig.url}" style="color:#31674e">toolgrain.com</a></td></tr></table></body></html>`;
 return {subject:'Welcome to Toolgrain Pro',html,text};
}
