import { pageMetadata } from '@/config/metadata';
import { Container } from '@/components/ui/shared';
export const metadata = pageMetadata('Privacy Policy | Toolgrain', 'Website requests, account authentication, local CSV processing and email contact.', '/privacy');
// Owner details supplied by the operator. Verify hosting/email setup,
// retention criteria and contractual transfer safeguards before launch.
export default function Page() {
 return <Container className="page-section prose-page">
 <p className="eyebrow">PRIVACY INFORMATION</p><h1 className="page-title">Privacy Policy</h1>
 <h2>1. Controller</h2><p>The controller responsible for this website is:</p>
 <dl className="legal-details"><dt>Full legal name</dt><dd>YANNICK KROLL</dd><dt>Postal address</dt><dd>HOLZER WEG 11, 58708 MENDEN, DEUTSCHLAND</dd><dt>Contact email</dt><dd>info@toolgrain.com</dd></dl>
 <h2>2. Hosting</h2><p>Toolgrain is hosted using Vercel, a US-based hosting provider with global infrastructure. Vercel delivers the website and may process technical request data for operation and security. Hosting is separate from local CSV processing.</p><p>Provider information is available in <a href="https://vercel.com/legal/privacy-notice">Vercel’s privacy notice</a>. This describes Vercel’s own practices; deployment-specific contractual terms and settings must also be considered.</p>
<h2>3. Server / access data</h2><p>Normal website delivery may involve your IP address, request time, requested resource, browser or user-agent information, and technical log or diagnostic data. These data support delivery, reliability, troubleshooting and protection against misuse. They are separate from selected CSV file contents.</p>
<h2>4. Local CSV processing</h2><p>Selected CSV files are read and parsed in your browser. CSV file contents are not intentionally transmitted to Toolgrain’s application server. CRM analysis and cleaning, CSV comparison, Shopify supplier mapping and corrections, and CSV export happen locally in the browser. Selected files, parsed rows, cleaned data, comparison results and product contents are not sent to Supabase. No Toolgrain account is required to use the Free tools.</p><p>Working data is held in browser memory, rather than persistent application browser storage. Export creates a local download when you choose it. Resetting the tool or leaving the page releases the application’s working state; downloaded files remain wherever you save them. Ordinary requests for the website still reach hosting infrastructure.</p>
<h2>5. Cookies and local storage</h2><p>When account access is configured and you sign in, essential authentication cookies maintain and refresh your Supabase session. Confirmation and magic-link flows may also use a temporary cookie to complete sign-in. These cookies are used for account access, not advertising or tracking. The current application does not use localStorage or sessionStorage to retain CSV contents or account data. Auth forms use server actions and cookie-based sessions. Your browser may cache website resources and save downloaded files. No non-essential browser storage or consent banner is added. Free tools remain usable without signing in.</p>
<h2>6. Analytics and tracking</h2><p>Toolgrain currently does not use its own analytics or advertising tracking. No Vercel Analytics, Speed Insights, tracking pixels, externally loaded third-party scripts or embedded third-party content are integrated. The Supabase SDK supports account authentication; it is separate from analytics. Hosting-provider operational logs are separate from Toolgrain analytics.</p>
<h2>7. Contact by email</h2><p>If you contact Toolgrain by email, the information you send, including your email address, message and any attachments, is processed to respond to your request. There is no contact form. Email is handled through the email services used by the sender and recipient, separately from the CRM CSV Cleaner. Please send only information needed for your enquiry.</p>
<h2>Account data and authentication</h2><p>Where account access is enabled, Toolgrain uses Supabase Auth and Supabase Postgres for account information. This includes your email address, authentication identifiers, account creation and update timestamps, and plan identity. Email/password authentication or an email sign-in link is used to provide access. Password authentication is handled by Supabase; Toolgrain does not implement its own password storage. Account-related technical request and security data may also be processed. Account data may be stored server-side; CSV contents remain local.</p><p>New accounts use the Free plan. There is no payment system, saved CSV history or cloud file storage. See <a href="https://supabase.com/privacy">Supabase’s privacy notice</a> for provider information. Project region, processing terms, email delivery and relevant safeguards must be verified for the configured service before enabling public account registration.</p><h2>8. Legal bases</h2><p>Website delivery and security are generally based on Article 6(1)(f) GDPR: the legitimate interest in operating a reliable, secure website. Email enquiries are generally handled on the same basis, with the interest in responding to enquiries, or under Article 6(1)(b) where needed for a contract or steps requested before entering one. Article 6(1)(c) applies where a legal duty requires retention or disclosure. Where processing relies on consent, Article 6(1)(a) applies.</p><p>Account creation and requested account access are generally based on Article 6(1)(b) GDPR where necessary to provide the requested account service. Account security and abuse prevention are generally based on Article 6(1)(f), with the interest in protecting accounts and operating a reliable service.</p><p>Local CSV processing is performed at your request on your device. If your CSV contains personal data about others, you remain responsible for having an appropriate basis for your use of those data.</p>
<h2>9. Data retention</h2><p>Website access and diagnostic data are retained according to the applicable hosting configuration, operational need and contractual requirements. No specific Vercel retention period is asserted here. Email correspondence is retained as needed to handle the enquiry and follow-up, and longer where legal retention duties or the establishment, exercise or defence of legal claims require it. Data should otherwise be deleted when no longer needed.</p><p>Account information is retained while needed to provide your account, and longer where legal duties or claims require it. Session duration, authentication logs and backups depend on the Supabase configuration; no unverified fixed retention period is asserted. You can contact the controller to request applicable access or deletion rights.</p><p>Toolgrain does not retain selected CSV contents on its application server. Local working state and exported files are described in section 4.</p>
<h2>10. Recipients / processors</h2><p>Vercel and service providers involved in website delivery may receive technical request data. Supabase and configured authentication email-delivery providers may process account and authentication data. Email service providers may process correspondence. Access is limited to what is needed for the respective purpose; disclosures may also be required by law. Where providers act as processors, applicable processing terms must govern their handling of personal data.</p>
<h2>11. International transfers</h2><p>Transfers outside the European Economic Area may occur depending on the services and infrastructure used, including Vercel, Supabase services and the email services involved. Applicable safeguards are relied upon where required. The exact mechanism depends on the relevant contract, service and destination and must be verified for this deployment; this notice does not assert a particular mechanism or exclusively German or EU processing. You may ask the controller about applicable safeguards and how to obtain a copy.</p>
<h2>12. Data subject rights</h2><p>Subject to GDPR conditions and exceptions, you may request access, rectification, erasure, restriction and data portability. You may object to processing based on legitimate interests on grounds relating to your particular situation. Where processing is based on consent, you may withdraw it at any time without affecting prior lawful processing. Contact the controller above to exercise applicable rights.</p>
<h2>13. Right to complain to a supervisory authority</h2><p>You may complain to a data protection supervisory authority, particularly in the EU Member State of your habitual residence, place of work or the alleged infringement, if you believe processing infringes the GDPR.</p><p>For an operator established in North Rhine-Westphalia, <a href="https://www.ldi.nrw.de/kontakt/ihre-beschwerde">LDI NRW</a> may be the relevant authority.</p>
<h2>14. Changes to this privacy notice</h2><p>This notice will be updated when the website’s processing or relevant requirements change. Future tools or integrations may involve different data handling. The current version is published on this page.</p>
 </Container>;
}
