'use client';
import {BrandLogo} from '@/components/brand/brand-logo';
import React,{useActionState} from 'react';
import Link from 'next/link';
import {loginAction,signupAction,magicLinkAction} from '../../app/auth/actions';
import type {AuthState} from '../../lib/auth/errors';
export function AuthForm({mode,next,available,notice}:{mode:'login'|'signup';next:string;available:boolean;notice?:string}){
 const [state,action,pending]=useActionState<AuthState,FormData>(mode==='login'?loginAction:signupAction,{});
 const [magic,magicAction,magicPending]=useActionState<AuthState,FormData>(magicLinkAction,{});
 return <section className="auth-card" aria-label={mode==='login'?'Sign in to Toolgrain':'Create a Toolgrain account'}><div className="auth-brand"><BrandLogo compact /></div><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p className="muted">{mode==='login'?'Sign in to Toolgrain.':'Free tools work without an account. Accounts prepare the way for Pro.'}</p>{!available&&<p role="status" className="compare-warning">Account sign-in is not available yet. You can still use all Free tools without an account.</p>}{notice&&<p role="alert">{notice}</p>}<form action={action}><input type="hidden" name="next" value={next}/><label htmlFor={mode+'-email'}>Email<input id={mode+'-email'} name="email" type="email" autoComplete="email" maxLength={254} required disabled={!available||pending}/></label><label htmlFor={mode+'-password'}>Password<input id={mode+'-password'} name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='signup'?8:undefined} maxLength={256} required disabled={!available||pending}/></label>{state.error&&<p role="alert">{state.error}</p>}{state.message&&<p role="status">{state.message}</p>}<button className="button" type="submit" disabled={!available||pending}>{pending?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form>{mode==='login'&&<details className="auth-magic"><summary>Email me a sign-in link</summary><form action={magicAction}><input type="hidden" name="next" value={next}/><label htmlFor="magic-email">Email<input id="magic-email" name="email" type="email" autoComplete="email" maxLength={254} required disabled={!available||magicPending}/></label><button type="submit" className="button secondary" disabled={!available||magicPending}>{magicPending?'Sending…':'Send magic link'}</button>{magic.error&&<p role="alert">{magic.error}</p>}{magic.message&&<p role="status">{magic.message}</p>}</form></details>}<p className="auth-links"><Link href={(mode==='login'?'/signup':'/login')+'?next='+encodeURIComponent(next)}>{mode==='login'?'Create an account':'Already have an account? Sign in'}</Link> · <Link href="/tools">Continue with Free tools</Link></p></section>;
}
